#!/bin/sh
set -e

# Professional Entrypoint Script
echo "----------------------------------------------------"
echo "🚀 Starting Cortex Visual Commander"
echo "🕒 Time: $(date)"
echo "----------------------------------------------------"

# 1. Run migrations if enabled
if [ "$SKIP_MIGRATIONS" != "true" ]; then
    echo "📦 [Migration] Running database migrations..."
    # Using npx prisma migrate deploy for production-safe migrations
    if npx prisma migrate deploy; then
        echo "✅ [Migration] Migrations applied successfully."
    else
        echo "❌ [Migration] Migration failed. Checking if database is reachable..."
        # Optional: Add retry logic or health check here
    fi
else
    echo "⏭️  [Migration] Skipping migrations as per SKIP_MIGRATIONS=true"
fi

# 2. Start the application
echo "⚡ [Server] Starting application server..."
# The 'server.js' is generated by Next.js standalone output
exec node server.js
